storage_directory: "/home/pi/Documents/temp_daq/"
interval: 2
status_led: true
status_led_pin: 21
sensors:
  - name: sensor1
    id: 00000c43b797
  - name: sensor2
    id: 00000c442341
  - name: sensor3
    id: 00000c4419a8